---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
actData<-read.csv("activity.csv")
 actDate0<-as.Date(actData$date)
 actData$date<-actDate0
```

## What is mean total number of steps taken per day?
```{r}
sumSteps<-group_by(actData, date)%>%summarize(totSteps=sum(steps,na.rm=TRUE))
hist(sumSteps$totSteps)
meanDailySteps<-mean(sumSteps$totSteps)
medianDailySteps<-median(sumSteps$totSteps)
```


## What is the average daily activity pattern?
```{r}
 grByInt<-group_by(actData, as.numeric(row.names(actData))%%288)
what<-summarize(grByInt, mean(steps, na.rm=TRUE))
names(what)<-c("interval","steps")
plot(x=what$interval,y=what$steps, type="l")
tablewhat[which.max(what$steps),]
```


## Imputing missing values
```{r}
sum(is.na(actData$steps))
newActData<-grByInt
newActData$steps[is.na(newActData$steps)] <- what$steps[newActData$intGrp]

sumStepsNew<-group_by(newActData, date)%>%summarize(totSteps=sum(steps,na.rm=TRUE))
hist(sumStepNew$totSteps)
meanDailyStepsNew<-mean(sumStepsNew$totSteps)
medianDailyStepsNew<-median(sumStepsNew$totSteps)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
 newActData$daytype <- as.factor(ifelse(weekdays(newActData$date)=='Sunday'|weekdays(newActData$date)=='Saturday', 'weekend','weekday'))
grByIntWd<-group_by(newActData, daytype, as.numeric(row.names(newActData))%%288)
nowwhat<-summarize(grByIntWd, mean(steps, na.rm=TRUE))
names(nowwhat)<-c("daytype","interval","steps")
p9<-ggplot(nowwhat)+geom_line(mapping=aes(x=interval, y=steps))+facet_grid(~daytype)
print(p9)
```
